export const demoSermons = [
  {
    id: 'demo-kingdom-greatness',
    slug: 'gods-kingdom-redefines-greatness',
    title: "God's Kingdom Redefines Greatness",
    scripture: 'Philippians 2:1–11',
    scriptureBook: 'Philippians',
    seriesTitle: 'The Kingdom Turns Everything Around',
    seriesSlug: 'the-kingdom-turns-everything-around',
    datePreached: '2026-07-12',
    duration: '8 min',
    speaker: 'Christopher Shelley',
    status: 'published',
    featured: true,
    youtubeId: '',
    summary: 'The world measures greatness by power, recognition, and control. Philippians 2 reveals that Jesus turns every one of those measurements upside down.',
    bigIdea: "God's kingdom redefines greatness through the humility of Jesus.",
    topics: ['Humility', 'Jesus', 'Kingdom of God'],
    outline: ['Greatness begins when we stop grasping for position.', 'Greatness takes the form of humble service.', 'Greatness trusts God with the outcome.'],
    notes: [
      { heading: 'The Pattern We Usually Follow', paragraphs: ['We are trained to notice the person at the top, the loudest voice in the room, and the name receiving the most recognition. Philippians 2 asks us to look in another direction.', 'Paul points the church toward the mind of Christ. Jesus possessed every right to glory, yet He did not use His position for selfish advantage.'] },
      { heading: 'The Kingdom Turns Everything Around', paragraphs: ['Jesus moved downward in service before the Father lifted Him up in honor. The cross was not a detour from His greatness; it revealed what divine greatness truly looks like.', 'Christians do not become small because they lack value. We choose humility because our value is secure in Christ.'] },
      { heading: 'Living the Passage', paragraphs: ['The question is not whether people notice our service. The question is whether our lives make the character of Jesus visible.', 'God’s kingdom redefines greatness, and every act of faithful humility becomes a witness to the King who served us first.'] },
    ],
  },
  {
    id: 'demo-christ-enough',
    slug: 'live-like-christ-is-enough',
    title: 'Live Like Christ Is Enough',
    scripture: 'Colossians 3:1–17',
    scriptureBook: 'Colossians',
    seriesTitle: 'Christ Is Enough',
    seriesSlug: 'christ-is-enough',
    datePreached: '2026-07-19',
    duration: '24 min',
    speaker: 'Christopher Shelley',
    status: 'published',
    featured: false,
    youtubeId: '',
    summary: 'Because believers have been raised with Christ, ordinary habits, relationships, words, and priorities should begin to look like Him.',
    bigIdea: 'When Christ is enough, every part of life comes under His rule.',
    topics: ['Discipleship', 'Identity', 'Christian Living'],
    outline: ['Set your mind where Christ is.', 'Put to death what does not belong to Christ.', 'Put on the character of Christ.'],
    notes: [
      { heading: 'A New Direction', paragraphs: ['Paul does not begin with a list of better habits. He begins with a new identity: you have been raised with Christ.', 'Christian obedience grows out of belonging. We seek what is above because our life is now hidden with Christ in God.'] },
      { heading: 'A New Wardrobe', paragraphs: ['Compassion, kindness, humility, gentleness, patience, forgiveness, and love are not accessories. They are the visible clothing of a life shaped by Jesus.'] },
    ],
  },
  {
    id: 'demo-choosing-joy',
    slug: 'choosing-joy',
    title: 'Choosing Joy',
    scripture: 'Habakkuk 3:17–19',
    scriptureBook: 'Habakkuk',
    seriesTitle: 'Faith When Life Shakes',
    seriesSlug: 'faith-when-life-shakes',
    datePreached: '2026-07-20',
    duration: '31 min',
    speaker: 'Christopher Shelley',
    status: 'published',
    featured: false,
    youtubeId: '',
    summary: 'Habakkuk shows that biblical joy is not denial. It is a deliberate confidence in God when the visible evidence is painful.',
    bigIdea: 'Joy is possible when God remains our strength, even when circumstances change.',
    topics: ['Joy', 'Suffering', 'Faith'],
    outline: ['Name the loss honestly.', 'Choose where your confidence will rest.', 'Let God become your strength for the next step.'],
    notes: [
      { heading: 'Faith Does Not Pretend', paragraphs: ['Habakkuk names the empty fields, failed crops, and missing livestock. His joy is not built on pretending that the losses are small.'] },
      { heading: 'Yet I Will Rejoice', paragraphs: ['The word “yet” becomes a hinge. Everything before it describes the crisis; everything after it declares where Habakkuk will place his trust.'] },
    ],
  },
  {
    id: 'demo-storm',
    slug: 'faithful-in-the-storm',
    title: 'Faithful in the Storm',
    scripture: 'Acts 27:13–26',
    scriptureBook: 'Acts',
    seriesTitle: 'Paul: Faith on the Move',
    seriesSlug: 'paul-faith-on-the-move',
    datePreached: '2026-06-28',
    duration: '22 min',
    speaker: 'Christopher Shelley',
    status: 'published',
    featured: false,
    youtubeId: '',
    summary: 'Paul could not calm the sea, but he could stand in the storm with a word of courage rooted in the promise of God.',
    bigIdea: 'Faithfulness means trusting what God has said when the storm says otherwise.',
    topics: ['Courage', 'Trust', 'Paul'],
    outline: ['The storm exposes our limits.', 'God is present before the rescue arrives.', 'Courage can steady an entire room.'],
    notes: [{ heading: 'When Control Disappears', paragraphs: ['The crew had experience, equipment, and determination, but none of it could command the sea. The storm forced everyone to confront the limits of human control.'] }],
  },
  {
    id: 'demo-unknown-god',
    slug: 'answering-the-unknown-god',
    title: 'Answering the Unknown God',
    scripture: 'Acts 17:22–31',
    scriptureBook: 'Acts',
    seriesTitle: 'Paul: Faith on the Move',
    seriesSlug: 'paul-faith-on-the-move',
    datePreached: '2026-06-21',
    duration: '18 min',
    speaker: 'Christopher Shelley',
    status: 'published',
    featured: false,
    youtubeId: '',
    summary: 'Paul begins with the Athenians’ unanswered question and announces the God who made, sustains, and calls every person.',
    bigIdea: 'The unknown God is the Creator who has made Himself known through Jesus.',
    topics: ['Apologetics', 'Gospel', 'Paul'],
    outline: ['God made everything.', 'God is near to every person.', 'God has made Himself known in the risen Jesus.'],
    notes: [{ heading: 'Beginning With the Question', paragraphs: ['Paul notices the altar, but he does not leave the Athenians in uncertainty. He uses their question as a doorway to proclaim the Creator.'] }],
  },
  {
    id: 'demo-rescued',
    slug: 'rescued',
    title: 'Rescued',
    scripture: 'Daniel 6',
    scriptureBook: 'Daniel',
    seriesTitle: 'Heroes of Faith',
    seriesSlug: 'heroes-of-faith',
    datePreached: '2026-06-14',
    duration: '20 min',
    speaker: 'Christopher Shelley',
    status: 'published',
    featured: false,
    youtubeId: '',
    summary: 'Daniel’s rescue begins before the lions’ den—with a life of steady faithfulness that could not be hidden or negotiated away.',
    bigIdea: 'God is worthy of faithfulness before, during, and after the danger.',
    topics: ['Daniel', 'Rescue', 'Faithfulness'],
    outline: ['Faithfulness becomes a pattern.', 'Pressure reveals what we worship.', 'God remains present in the den.'],
    notes: [{ heading: 'A Faith That Was Already There', paragraphs: ['Daniel did not invent a prayer life when the law changed. The crisis revealed the faithfulness he had practiced all along.'] }],
  },
];

export const demoSeries = [
  { id: 'series-kingdom', slug: 'the-kingdom-turns-everything-around', title: 'The Kingdom Turns Everything Around', description: 'A focused look at how the life and lordship of Jesus overturn the world’s definitions of power, success, and greatness.', published: true, order: 1 },
  { id: 'series-christ-enough', slug: 'christ-is-enough', title: 'Christ Is Enough', description: 'Teaching through Colossians about the supremacy of Jesus and the life that grows from belonging completely to Him.', published: true, order: 2 },
  { id: 'series-faith-shakes', slug: 'faith-when-life-shakes', title: 'Faith When Life Shakes', description: 'Habakkuk’s honest journey from questions and fear toward worship, trust, and resilient joy.', published: true, order: 3 },
  { id: 'series-paul', slug: 'paul-faith-on-the-move', title: 'Paul: Faith on the Move', description: 'Messages from Acts exploring courage, mission, suffering, and the unstoppable movement of the gospel.', published: true, order: 4 },
  { id: 'series-heroes', slug: 'heroes-of-faith', title: 'Heroes of Faith', description: 'Old Testament stories that point beyond human bravery toward the faithfulness and rescuing power of God.', published: true, order: 5 },
];
